# Generated by Django 4.2 on 2024-02-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_topic_blog_blogidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='wordCount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
