# Generated by Django 4.2 on 2024-02-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_profile_monthlycount_profile_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
